# Application
spring.application.name=mls
spring.threads.virtual.enabled=true

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/mls
spring.datasource.username=ma-sum
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.default_schema=mls

# Flyway
spring.flyway.enabled=true
spring.flyway.schemas=mls
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0

# ==================== LOGGING CONFIG ====================

# Level logging
logging.level.root=INFO
logging.level.com.masum=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Structured Logging (JSON + ECS format)
logging.structured.format.console=ecs
logging.structured.format.file=ecs

# Nama file log (opsional)
logging.file.name=logs/app.log

# Pattern fallback kalau structured tidak aktif
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [%X{traceId}] [%X{userId}] - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [%X{traceId}] [%X{userId}] - %msg%n

# Tambahan informasi di structured log
logging.structured.ecs.service.name=mls
logging.structured.ecs.service.version=1.0.0

# MDC keys yang akan otomatis masuk ke JSON (Spring Boot otomatis baca)
logging.structured.ecs.include.mdc-keys=traceId,userId,requestUri,method
